config/routes.rb
Rails.application.routes.draw do

  scope :administrator do
    resources :cate_blogs
    resources :blogs
    resources :teams
    resources :services
    resources :portfolios
    resources :category_portfolios
    resources :resumes
    resources :category_resumes
    resources :skills
    resources :profiles
    devise_for :users
    resources :users
    get "dashboard" => 'dashboards#index', :as => :dashboard_page
  end

  resources :news
  root "homes#index"


end

app/models/blog.rb
class Blog < ApplicationRecord
  before_save :update_slug
  #Associations
  belongs_to :cate_blog
  belongs_to :user

  #validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instace method
  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
end

app/models/cate_blog.rb
class CateBlog < ApplicationRecord
  belongs_to :user
  has_many :blogs
end

app/models/category_resume.rb
class CategoryResume < ApplicationRecord
  has_many :resumes
  belongs_to :user
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  belongs_to :category_portfolio

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :skills, inverse_of: :profile
  belongs_to :user
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :category_resume
  accepts_nested_attributes_for :category_resume
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

app/models/service.rb
class Service < ApplicationRecord
   belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :profile, required: false
  belongs_to :user,required: false
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Association
  has_many :profiles
  has_many :category_resumes
  has_many :category_portfolios
  has_many :portfolios
  has_many :resumes
  has_many :services
  has_many :skills
  has_many :teams
  has_many :blogs
  has_many :cate_blogs
  #Devise
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  #Validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instance method
  def set_default_role
    self.role ||= :user
  end

  def full_name
    "#{first_name}" "#{last_name}"
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cate_blogs_helper.rb
module CateBlogsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def full_name(profile)
    "#{profile.first_name} #{profile.last_name}"
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_left-panel.html.erb
<div class="leftpanel">
  <div class="media profile-left">
    <%if user_signed_in?%>
      <%=link_to users_path,:class=>"pull-left profile-thumb" do%>
      <%if current_user.image.blank?%>
        <img class="img-circle" src="/profile.png" alt="">
      <%else%>
        <img class="img-circle" src="<%=current_user.image%>" alt="">
      <%end%>
    <%end%>

    <div class="media-body">

      <h4 class="media-heading"><%=current_user.username%></h4>
        <span class="user-options">
          <%=link_to users_path do%>
            <i class="glyphicon glyphicon-user"></i>
          <%end%>
          <%=link_to edit_user_registration_path do%>
            <i class="glyphicon glyphicon-cog"></i>
          <%end%>
          <%=link_to destroy_user_session_path do%>
            <i class="glyphicon glyphicon-log-out"></i>
          <%end%>

        </span>
    </div>
    <%end%>

  </div><!-- media -->


  <ul class="nav nav-pills nav-stacked">
    <li class="active">
      <%=link_to dashboard_page_path do%>
        <i class="fa fa-home"></i>
        <span>Dashboard</span>
      <%end%>
    </li>
    <li class="parent">
      <a href="#">
        <i class="fa fa-suitcase"></i>
        <span>Profile</span>
      </a>

      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add New Profile", new_profile_path%>
          </li>
          <li>
            <%=link_to "Profile List", profiles_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Profile List", profiles_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent">
      <a href="#">
        <i class="fa fa-suitcase"></i>
        <span>Skill</span>
      </a>

      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add New Skill", new_skill_path%>
          </li>
          <li>
            <%=link_to "Skill List", skills_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Profile List", skills_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent">
      <a href="#">
        <i class="fa fa-suitcase"></i>
        <span>Resume</span>
      </a>

      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add New Resume", new_resume_path%>
          </li>
          <li>
            <%=link_to "Add Category", new_category_resume_path%>
          </li>
          <li>
            <%=link_to "Resume List", resumes_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Resume List", resumes_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent">
      <a href="#">
        <i class="fa fa-suitcase"></i>
        <span>Portfolio</span>
      </a>

      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add New Resume", new_portfolio_path%>
          </li>
          <li>
            <%=link_to "Add Category", new_category_portfolio_path%>
          </li>
          <li>
            <%=link_to "Resume List", portfolios_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Resume List", portfolios_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent">
      <a href="#">
        <i class="fa fa-suitcase"></i>
        <span>My Team</span>
      </a>

      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add New Team", new_team_path%>
          </li>
          <li>
            <%=link_to "Team List", teams_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Team List", teams_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent">
      <a href="#">
        <i class="fa fa-suitcase"></i>
        <span>Blog</span>
      </a>

      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add New Blog", new_blog_path%>
          </li>
          <li>
            <%=link_to "Add Category", new_cate_blog_path%>
          </li>
          <li>
            <%=link_to "Blog List", blogs_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Blog List", blogs_path%>
          </li>
        <%end%>

      </ul>
    </li>

  </ul>
</div><!-- leftpanel -->

app/views/shared/_navbar.html.erb
<header>
  <div class="headerwrapper">
    <div class="header-left">
      <a href="/admin" class="logo">
        <h4 class="admin-logo"><img src="/logo.png" alt=""> Administrator </h4>

      </a>

      <div class="pull-right">
        <a href="#" class="menu-collapse">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div><!-- header-left -->

    <div class="header-right">
      <div class="pull-right">
        <!-- <form class="form form-search" action="http://www.ravijaiswal.com/Moldavite/search-results.html">
          <input type="search" class="form-control" placeholder="Search" />
        </form> -->

        <div class="btn-group btn-group-option">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <%if user_signed_in?%>
              <%if current_user.image.blank?%>
                  <img class="img-circle avatar-img" alt="" src="/profile.png">
                <%else%>
                  <img class="img-circle avatar-img" alt="" src="<%=current_user.image%>">
              <%end%>
              <%else%>
            <%end%>
        		<span class="user-name"><%=current_user.username%></span>
        		<i class="fa fa-caret-down"></i>
          </button>
          <ul class="dropdown-menu pull-right" role="menu">
            <% if user_signed_in? %>
              <% if current_user.try(:admin?) %>
                <li>
                  <%= link_to current_user do %>
                    <i class="glyphicon glyphicon-user"></i>
                    My Profile
                  <%end%>
                  </li>
              <% end %>
            <% end %>

              <% if user_signed_in? %>
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="glyphicon glyphicon-cog"></i>
                    Change Password
                  <%end%>
                </li>

                <li>
                  <%= link_to destroy_user_session_path, :method => 'delete' do %>
                    <i class="glyphicon glyphicon-log-out"></i>
                    Sign Out
                  <%end%>
                </li>
              <% else %>

              <% end %>
          </ul>
        </div><!-- btn-group -->
      </div><!-- pull-right -->
    </div><!-- header-right -->
  </div><!-- headerwrapper -->
</header>

app/views/shared/google-font/_font.html.erb
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 

app/views/shared/javascription/_javascript-partial.html.erb
<%= render "shared/javascription/1.plugins.html.erb"%>
<%= render "shared/javascription/2.jwplayer.html.erb"%>
<%= render "shared/javascription/3.components.html.erb"%>

app/views/shared/style/_8.ie9.html.erb
<style media="screen">
  .sweet-alert .icon.error .line.left{-ms-transform:rotate(45deg)\9}.sweet-alert .icon.error .line.right{-ms-transform:rotate(-45deg)\9}.sweet-alert .icon.success{border-color:transparent\9}.sweet-alert .icon.success .line.tip{-ms-transform:rotate(45deg)\9}.sweet-alert .icon.success .line.long{-ms-transform:rotate(-45deg)\9}
</style>

app/views/shared/style/_style-partial.html.erb
<%= render "shared/style/1.material-design-iconic-font.min.html.erb"%>
<%= render "shared/style/2.ionicons.min.html.erb"%>
<%= render "shared/style/3.material.min.html.erb"%>
<%= render "shared/style/4.owl.carousel.min.html.erb"%>
<%= render "shared/style/5.owl.theme.default.min.html.erb"%>
<%= render "shared/style/6.magnific-popup.html.erb"%>
<%= render "shared/style/7.sweet-alert.min.html.erb"%>
<%= render "shared/style/8.ie9.html.erb"%>
<%= render "shared/style/9.1.animate.min.html.erb"%>
<%= render "shared/style/9.common.html.erb"%>
<%= render "shared/style/10.main.html.erb"%>