config/routes.rb
Rails.application.routes.draw do

  scope :administrator do
    resources :cate_blogs
    resources :blogs
    resources :teams
    resources :services
    resources :portfolios
    resources :category_portfolios
    resources :resumes
    resources :category_resumes
    resources :skills
    resources :profiles
    devise_for :users
    resources :users
    get "dashboard" => 'dashboards#index', :as => :dashboard_page
  end

  resources :news
  root "homes#index"


end

app/models/blog.rb
class Blog < ApplicationRecord
  before_save :update_slug
  #Associations
  belongs_to :cate_blog
  belongs_to :user

  #validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instace method
  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
end

app/models/cate_blog.rb
class CateBlog < ApplicationRecord
  belongs_to :user
  has_many :blogs
end

app/models/category_resume.rb
class CategoryResume < ApplicationRecord
  has_many :resumes
  belongs_to :user
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  belongs_to :category_portfolio

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :skills, inverse_of: :profile
  belongs_to :user
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :category_resume
  accepts_nested_attributes_for :category_resume
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

app/models/service.rb
class Service < ApplicationRecord
   belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :profile, required: false
  belongs_to :user,required: false
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Association
  has_many :profiles
  has_many :category_resumes
  has_many :category_portfolios
  has_many :portfolios
  has_many :resumes
  has_many :services
  has_many :skills
  has_many :teams
  has_many :blogs
  has_many :cate_blogs
  #Devise
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  #Validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instance method
  def set_default_role
    self.role ||= :user
  end

  def full_name
    "#{first_name}" "#{last_name}"
  end
end

app/controllers/news_controller.rb
class NewsController < NewBootstrapController
  before_action :set_news, only: [:show]
  def index
    @blogs = Blog.all
    @recent = Blog.order('created_at DESC').limit(5)
    @category = CateBlog.all.limit(5)
  end

  def show
  end


  private
    def set_news
      @blog = Blog.find_by_slug(params[:id])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cate_blogs_helper.rb
module CateBlogsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def full_name(profile)
    "#{profile.first_name} #{profile.last_name}"
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/news/_footer.html.erb
<footer class="footer">
    <section class="footer__top">
        <div class="container">
            <div class="footer__top__inner text-center">
                <a href="index-2.html" class="m-b-xxs-30 m-b-md-40 wow fadeInDownSmall"><img src="img/logo/footer-logo.png" alt="footer-logo"></a>
                <ul>
                    <li class="wow fadeInUpSmall"><a href="javascript:void(0)"><i class="fa fa-facebook"></i></a></li>
                    <li class="wow fadeInUpSmall" data-wow-delay=".1s"><a href="javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                    <li class="wow fadeInUpSmall" data-wow-delay=".2s"><a href="javascript:void(0)"><i class="fa fa-google-plus"></i></a></li>
                    <li class="wow fadeInUpSmall" data-wow-delay=".3s"><a href="javascript:void(0)"><i class="fa fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </section>
    <section class="footer__bottom">
        <div class="container">
            <div class="footer__bottom__text text-center">
                <p>Chhouk Tit Panhara &copy; 2017-2018. All Rights Reserved.</p>
            </div>
        </div>
    </section>
</footer>
<button id="backToTop" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect back-to-top shade-on hide-right"><i class="fa fa-angle-down"></i></button>

app/views/news/_navigation.html.erb
<div id="loader" class="preloader">
    <div class="preloader__inner"></div>
</div>

<div class="mobile-menu-trigger visible-sm visible-xs visible-xxs">
    <button class="hamburger hamburger--spin" type="button"><span class="hamburger-box"><span class="hamburger-inner"></span></span>
    </button>
</div>

<header class="site-navbar">
    <a href="index-2.html" class="site-logo"><img class="site-logo__image-1" src="/logo1.png" alt="logo-1"> <img class="site-logo__image-2" src="/logo2.png" alt="logo-2"></a>
    <nav class="site-nav hidden-xxs hidden-xs hidden-sm">
        <ul class="cl-effect-5">
            <li><a href="/"><span data-hover="Home"><span>Home</span></span></a></li>
            <li><a href="/portfolio" ><span data-hover="Portfolio"><span>Portfolio</span></span></a></li>
            <li><a href="/news" ><span data-hover="Blog"><span>Blog</span></span></a></li>
            <li><a href="/contact" ><span data-hover="Contact"><span>Contact</span></span></a></li>
        </ul>
    </nav>
</header>

app/views/news/index.html.erb
<%=render "navigation"%>
    <section class="banner banner--small section-main overflow-hidden">
        <div class="bg-parallax" data-top="transform: translate3d(0px, 0px, 0px); opacity: 1;" data-top-bottom="transform: translate3d(0px, 250px, 0px); opacity: 0;"></div>
        <div class="banner__v-center">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="banner__content">
                            <div class="banner__content__text">
                                <h2 class="wow fadeInLeftSmall">Blog Standard</h2>
                                <p class="wow fadeInLeftSmall" data-wow-delay=".3s">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, est.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="blog" class="blog-posts section-main section-padding section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-7 col-md-8">
                            <div class="row">
                                <div id="blog-posts-mesonary">

                                  <%@blogs.each do |blog|%>
                                    <article class="col-xxs-12 single-blog-post">
                                        <div class="mdl-card jumbo-shadow mdl-shadow--2dp">
                                            <div class="post-thumb-wrap"><img alt="Blog 1 Thumb" src="<%=blog.image%>">
                                                <div class="post-meta-info"><span class="post-meta-date"><%=blog.created_at%></span></div>
                                            </div>
                                            <div class="post-content-wrap">
                                                <h2 class="mdl-card__title-text mdl-card__title-content"><%=link_to blog.title, news_path(blog)%></a></h2>
                                                <div class="mdl-card__supporting-text">
                                                    <p><%=blog.description%></p>
                                                </div>
                                            </div>
                                            <div class="mdl-card__actions mdl-card--border"><a class="blog-comments" href="javascript:void(0)">5 Comments</a> <a class="blog-share" id="post-3"><i class="zmdi zmdi-share"></i></a>
                                                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect post-share-media js-post-share-media" data-for="post-3">
                                                    <li class="fb"><a href="single/single.html"><i class="zmdi zmdi-facebook-box"></i> <span>Facebook</span></a></li>
                                                    <li class="tw"><a href="single/single.html"><i class="zmdi zmdi-twitter-box"></i> <span>Twitter</span></a></li>
                                                    <li class="gplus"><a href="single/single.html"><i class="zmdi zmdi-google-plus-box"></i> <span>GooglePlus</span></a></li>
                                                    <li class="lin"><a href="single/single.html"><i class="zmdi zmdi-linkedin-box"></i> <span>LinkedIn</span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </article>
                                  <%end%>


                                </div>
                            </div>
                            <div class="text-center post-loader m-t-xs-30">
                                <a href="javascript:void(0)"><img src="../img/loadar.png" alt="loader"></a>
                            </div>
                        </div>
                        <div class="col-sm-5 col-md-4">
                            <aside class="sidebar">
                                <div class="sidebar__widget sidebar__widget--recent-posts">
                                    <h4 class="sidebar__widget__title">Recent Posts</h4>
                                    <ul>
                                      <%@recent.each do |recent|%>
                                        <li><%=link_to recent.title%><span><%=recent.created_at%></span></li>
                                      <%end%>

                                    </ul>
                                </div>
                                <div class="sidebar__widget sidebar__widget--categories">
                                    <h4 class="sidebar__widget__title">Categories</h4>
                                    <ul>
                                      <%@category.each do |category|%>
                                        <li><%=link_to category.category_name, "#"%></li>
                                      <%end%>
                                    </ul>
                                </div>

                            </aside>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<%=render "footer"%>

app/views/news/show.html.erb
<%=render "navigation"%>
    <section class="banner banner--small section-main overflow-hidden">
        <div class="bg-parallax" data-top="transform: translate3d(0px, 0px, 0px); opacity: 1;" data-top-bottom="transform: translate3d(0px, 250px, 0px); opacity: 0;"></div>
        <div class="banner__v-center">
            <div class="container">
                <div class="row">
                    <div class="col-xxs-12">
                        <div class="banner__content banner__content--2">
                            <div class="banner__content__text">
                                <h2 class="wow fadeInLeftSmall">Blog</h2>
                                <p class="wow fadeInLeftSmall" data-wow-delay=".3s">No Description</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="section-main section-padding section single-blog-post-content-container">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="single-blog-post-content"><img class="img-responsive" src="<%=@blog.image%>" alt="single-blog-post-content-image">
                                <h3><%=@blog.title%></h3>
                                <p><%=@blog.description%></p>

                            </div>
                        </div>

                        <div class="col-sm-4">
                            <aside class="sidebar">
                                <div class="sidebar__widget sidebar__widget--recent-posts">
                                    <h4 class="sidebar__widget__title">Recent Posts</h4>
                                    <ul>
                                        <li><a href="javascript:void(0)">We support any type of design</a> <span>October 24, 2015</span></li>
                                    </ul>
                                </div>
                                <div class="sidebar__widget sidebar__widget--categories">
                                    <h4 class="sidebar__widget__title">Categories</h4>
                                    <ul>
                                        <li><a href="javascript:void(0)">Google design</a></li>

                                    </ul>
                                </div>
                              
                            </aside>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<%=render "footer"%>