config/routes.rb
Rails.application.routes.draw do

  scope :administrator do
    resources :cate_blogs
    resources :blogs
    resources :teams
    resources :services
    resources :portfolios
    resources :category_portfolios
    resources :resumes
    resources :category_resumes
    resources :skills
    resources :profiles
    devise_for :users
    resources :users
    get "dashboard" => 'dashboards#index', :as => :dashboard_page
  end

  resources :news
  root "homes#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  before_save :update_slug
  #Associations
  belongs_to :cate_blog
  belongs_to :user

  #validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instace method
  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
end

app/models/cate_blog.rb
class CateBlog < ApplicationRecord
  belongs_to :user
  has_many :blogs
end

app/models/category_resume.rb
class CategoryResume < ApplicationRecord
  has_many :resumes
  belongs_to :user
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
  belongs_to :category_portfolio

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :skills, inverse_of: :profile
  belongs_to :user
  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :category_resume
  accepts_nested_attributes_for :category_resume
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
end

app/models/service.rb
class Service < ApplicationRecord
   belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :profile, required: false
  belongs_to :user,required: false
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Association
  has_many :profiles
  has_many :category_resumes
  has_many :category_portfolios
  has_many :portfolios
  has_many :resumes
  has_many :services
  has_many :skills
  has_many :teams
  has_many :blogs
  has_many :cate_blogs
  #Devise
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  #Validation
  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instance method
  def set_default_role
    self.role ||= :user
  end

  def full_name
    "#{first_name}" "#{last_name}"
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index,:show,:new,:edit,:update,:destroy]
  before_action :admin_only, only: [:new,:edit,:update,:destroy]
  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
    @fields = ["ID","Title","Category","Position","Start","Current","Description","Image"]
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = current_user.resumes.build
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = current_user.resumes.build(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Access denied."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:title, :position, :start_time, :current_time, :image,:description,:category_resume_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cate_blogs_helper.rb
module CateBlogsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def full_name(profile)
    "#{profile.first_name} #{profile.last_name}"
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/resumes/_all_data.html.erb
<thead>
  <tr>
    <%@fields.each do |f|%>
      <th><%=f%></th>
    <%end%>
  </tr>
</thead>

<%@resumes.each do |resume|%>
<tbody>
  <tr>
    <td><%=resume.id%></td>
    <td><%=resume.title%></td>
    <td><%=resume.category_resume.category_name%></td>
    <td><%=resume.position%></td>
    <td><%=resume.start_time%></td>
    <td><%=resume.current_time%></td>
    <td><%=resume.description%></td>
    <td style="width:20%;"><%=image_tag(resume.image,:class=>"img-table-data")%></td>
    <td class="table-action text-right">
			<%if current_user.try(:admin?)%>
				<%=link_to resume, :class => 'btn btn-success btn-simple btn-xs',:rel=>"tooltip",:title=>"View" do %>
					<i class="fa fa-eye" style="font-size: 15px;color:white"></i>
				<%end%>
				<%=link_to edit_resume_path(resume), :class => 'btn btn-success btn-simple btn-xs',:rel=>"tooltip",:title=>"Edit" do %>
					<i class="fa fa-pencil" style="font-size: 15px;color:white"></i>
				<%end%>
				<%=link_to resume,method: :delete,data: {confirm: "Are You Sure?"},:title=>"Delete", :class => 'btn btn-danger btn-simple btn-xs',:rel=>"tooltip",:title=>"Delete" do %>
					<i class="fa fa-trash-o" style="font-size: 15px;color:white"></i>
				<%end%>

			<%else%>
			   <%=link_to resume,:title=>"View",:class=>"tooltips" do %>
						<i class="fa fa-eye"></i>
				 <%end%>
      <%end%>
    </td>
  </tr>
</tbody>
<%end%>

app/views/resumes/_form.html.erb
<%=render "shared/navbar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <section class="panel panel-default">
            <div class="panel-body weather-row">
              <div class="row">
                <div class="col-md-12">
                  <%= form_for @resume do |f| %>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="panel-btns">
                                <a href="#" class="panel-minimize tooltips" data-toggle="tooltip" title="Minimize Panel"><i class="fa fa-minus"></i></a>
                                <a href="#" class="panel-close tooltips" data-toggle="tooltip" title="Close Panel"><i class="fa fa-times"></i></a>
                            </div><!-- panel-btns -->
                            <h4 class="panel-title">Add Product</h4>
                            <p>This is an example of a form using a placeholder instead of label.</p>
                        </div><!-- panel-heading -->
                        <div class="panel-body">
                            <div class="row">

                                <div class="form-group col-md-12">

                                    <%=f.collection_select :category_resume_id,CategoryResume.all,:id,:category_name%>

                                </div>

                                <div class="form-group col-md-4">
                                  <%= f.text_field :title,:class=>"form-control", placeholder:"Title",size:"20"%>
                                </div>
                                <div class="form-group col-md-4">
                                  <%= f.text_field :position , :class=>"form-control", placeholder:"Position",size:"20"%>
                                </div>
                                <div class="form-group col-md-4">
                                  <%= f.file_field :image , placeholder:"Phone",size:"20"%>
                                </div>
                                <div class="form-group col-md-6">
                                  <%= f.text_field :current_time , :class=>"form-control", :placeholder=>"mm/dd/yy", :id=>"datetimepicker1",size:"20"%>
                                </div>
                                <div class="form-group col-md-6">
                                  <%= f.text_field :start_time , :class=>"form-control", :placeholder=>"mm/dd/yy", :id=>"datetimepicker2",size:"20"%>
                                </div>
                                <div class="form-group col-md-12">
                                  <%= f.text_area :description , :class=>"form-control", placeholder:"Description",size:"20"%>
                                </div>

                            </div><!-- row -->
                        </div><!-- panel-body -->
                        <div class="panel-footer">
                          <%= f.submit "Create Profile", :class=>"btn btn-primary"%>
                        </div><!-- panel-footer -->
                    </div><!-- panel -->
                  <%end%>
                </div><!-- col-md-6 -->
              </div><!-- row -->
            </div>
          </section>

          <div class="row">
      			<div class="col-md-8">
      				<section class="panel panel-default">
      					<div class="panel-body weather-row">
      							<img src="/weather_image.jpg" height="243" alt="">
      							<div class="weather-head">
      								weather forecast
      							</div>
      							<div class="form-group country-select">
      								<select class="width100p" data-placeholder="New York">
      									<option value="">New York</option>
      									<option value="">London</option>
      									<option value="">Australia</option>
      									<option value="">Canada</option>
      									<option value="">China</option>
      									<option value="">New York</option>
      								</select>
      							</div>
      						</div>

      				<div class="panel-footer">
      					<div class="row weather-full-info">
      						<div class="col-md-3 today-status">
      							<h1>Today</h1>
      							<span class="wi wi-day-cloudy"></span>
      							<div class="degree">37</div>
      						</div>
      						<div class="col-md-9">
      							<ul>
      								<li>
      									<h2>Tomorrow</h2>
      									<span class="wi wi-day-cloudy text-primary"></span>
      									<div class="statistics">32</div>
      								</li>
      								<li>
      									<h2>Mon</h2>
      									<span class="wi wi-day-cloudy text-danger"></span>
      									<div class="statistics">40</div>
      								</li>
      								<li>
      									<h2>Tue</h2>
      									<span class="wi wi-day-cloudy text-info"></span>
      									<div class="statistics">25</div>
      								</li>
      								<li>
      									<h2>Wed</h2>
      									<span class="wi wi-day-cloudy text-success"></span>
      									<div class="statistics">37</div>
      								</li>
      								<li>
      									<h2>Thu</h2>
      									<span class="wi wi-day-cloudy text-warning"></span>
      									<div class="statistics">15</div>
      								</li>
      								<li>
      									<h2>Fri</h2>
      									<span class="wi wi-day-cloudy"></span>
      									<div class="statistics">21</div>
      								</li>
      							</ul>
      						</div>
      					</div>
      				</div>
      			</section>
      		</div>

      		<div class="col-md-4">
      			<section class="panel panel-default">
      				<div class="clock-panel">
      					<h1>DECEMBER 16</h1>
      					<p class="text-left">2016, Friday</p>
      					<p class="text-left">7:53 PM</p>
      				</div>

      				<ul id="clock">
      					<li id="sec"></li>
      					<li id="hour"></li>
      					<li id="min"></li>
      				</ul>

      				<ul class="clock-category">
      					<li>
      						<a href="#" class="active">
      							<i class="fa fa-clock-o"></i>
      							<span>Clock</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Alarm</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Stop watch</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Timer</span>
      						</a>
      					</li>
      				</ul>
      			</section>
      		</div>
      	</div>

      </div><!-- contentpanel -->

      <%=render "shared/footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>

app/views/resumes/_show_data.html.erb
<div class="row">
    <div class="col-md-5">
      <%=image_tag(@resume.image)%>
    </div>
    <div class="col-md-7">

        <h2 class="font-bold m-b-xs">
          <%=@resume.title%>
        </h2>
        <hr>

        <h4>NA</h4>
        <div class="small text-muted">
          <%=@resume.position%>
        </div>
        <hr>

        <h4>NA</h4>
        <div class="small text-muted">
          <%=@resume.start_time%>
        </div>
        <hr>

        <h4>NA</h4>
        <div class="small text-muted">
          <%=@resume.current_time%>
        </div>
        <hr>

        <h4>NA</h4>
        <div class="small text-muted">
          <%=@resume.description%>
        </div>
        <hr>
        <div class="btn-group">
          <% if current_user.try(:admin?) %>
            <%= link_to edit_resume_path, :class => 'btn btn-primary btn-sm',:rel=>"tooltip",:title=>"Edit",:style=>"margin-right:10px;" do %>
              <i class="fa fa-pencil" style="font-size: 15px;"></i> Edit Product
            <% end %>

            <%= link_to @resume,method: :delete,data: {confirm: "Are You Sure?"}, :class => 'btn btn-danger btn-sm',:rel=>"tooltip",:title=>"Delete" do %>
              <i class="fa fa-trash-o" style="font-size: 15px;"></i> Delete
            <% end %>
          <%end%>
        </div>
    </div>
</div>

app/views/resumes/edit.html.erb
<%= render 'form', resume: @resume %>

app/views/resumes/index.html.erb
<%=render "shared/navbar"%>

	<section>
			<div class="mainwrapper">
				<%=render "shared/left-panel"%>

					<div class="mainpanel">
							<div class="contentpanel contentpanel-wizard">
                <div class="row" style="background:#fff;padding:10px;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;margin-bottom:15px;">
                  <div class="col-md-12">
                    <h5 class="lg-title mb5">Table With Actions</h5>
                    <p class="mb20">An example of table with actions in every rows.</p>
                    <div class="table-responsive">
	                    <table class="table mb30">
	                      <%= render "all_data"%>
	                    </table>
                    </div><!-- table-responsive -->
                  </div><!-- col-md-6 -->
                </div>

                <div class="row">

                  <div class="col-md-8">
                    <section class="panel panel-default">
                      <div class="panel-body weather-row">
                        <img src="/weather_image.jpg" height="243" alt="">
                        <div class="weather-head">
                          weather forecast
                        </div>
                        <div class="form-group country-select">
                          <select class="width100p" data-placeholder="New York">
                            <option value="">New York</option>
                            <option value="">London</option>
                            <option value="">Australia</option>
                            <option value="">Canada</option>
                            <option value="">China</option>
                            <option value="">New York</option>
                          </select>
                        </div>
                      </div>

                  <div class="panel-footer">
                    <div class="row weather-full-info">
                      <div class="col-md-3 today-status">
                        <h1>Today</h1>
                        <span class="wi wi-day-cloudy"></span>
                        <div class="degree">37</div>
                      </div>
                      <div class="col-md-9">
                        <ul>
                          <li>
                            <h2>Tomorrow</h2>
                            <span class="wi wi-day-cloudy text-primary"></span>
                            <div class="statistics">32</div>
                          </li>
                          <li>
                            <h2>Mon</h2>
                            <span class="wi wi-day-cloudy text-danger"></span>
                            <div class="statistics">40</div>
                          </li>
                          <li>
                            <h2>Tue</h2>
                            <span class="wi wi-day-cloudy text-info"></span>
                            <div class="statistics">25</div>
                          </li>
                          <li>
                            <h2>Wed</h2>
                            <span class="wi wi-day-cloudy text-success"></span>
                            <div class="statistics">37</div>
                          </li>
                          <li>
                            <h2>Thu</h2>
                            <span class="wi wi-day-cloudy text-warning"></span>
                            <div class="statistics">15</div>
                          </li>
                          <li>
                            <h2>Fri</h2>
                            <span class="wi wi-day-cloudy"></span>
                            <div class="statistics">21</div>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </section>
              </div>

              <div class="col-md-4">
                <section class="panel panel-default">
                  <div class="clock-panel">
										<p><%=DateTime.now%></p>
                  </div>

                  <ul id="clock">
                    <li id="sec"></li>
                    <li id="hour"></li>
                    <li id="min"></li>
                  </ul>

                  <ul class="clock-category">
                    <li>
                      <a href="#" class="active">
                        <i class="fa fa-clock-o"></i>
                        <span>Clock</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Alarm</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Stop watch</span>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="fa fa-clock-o"></i>
                        <span>Timer</span>
                      </a>
                    </li>
                  </ul>
                </section>
              </div>
            </div>
					</div><!-- contentpanel -->
					<%=render "shared/footer"%>
				</div><!-- mainpanel -->
		</div><!-- mainwrapper -->
	</section>

app/views/resumes/new.html.erb
<%= render 'form', resume: @resume %>

app/views/resumes/show.html.erb
<%=render "shared/navbar"%>
<section>
  <div class="mainwrapper">
    <%=render "shared/left-panel"%>
      <div class="mainpanel">
        <div class="contentpanel">
          <section class="panel panel-default">
            <div class="weather-row">
            <div class="wrapper wrapper-content animated fadeInRight">
              <div class="row">
                  <div class="col-lg-12">

                      <div class="ibox product-detail">
                          <div class="ibox-content">
                            <%=render "show_data"%>
                          </div>
                          <div class="ibox-footer">
                              <span class="pull-right">

                              </span>
                              The description
                          </div>
                      </div>

                  </div>
              </div>
            </div>
            </div>
          </section>
          <div class="row">
      			<div class="col-md-8">
      				<section class="panel panel-default">
      					<div class="panel-body weather-row">
      							<img src="/weather_image.jpg" height="243" alt="">
      							<div class="weather-head">
      								weather forecast
      							</div>
      							<div class="form-group country-select">
      								<select class="width100p" data-placeholder="New York">
      									<option value="">New York</option>
      									<option value="">London</option>
      									<option value="">Australia</option>
      									<option value="">Canada</option>
      									<option value="">China</option>
      									<option value="">New York</option>
      								</select>
      							</div>
      						</div>

      				<div class="panel-footer">
      					<div class="row weather-full-info">
      						<div class="col-md-3 today-status">
      							<h1>Today</h1>
      							<span class="wi wi-day-cloudy"></span>
      							<div class="degree">37</div>
      						</div>
      						<div class="col-md-9">
      							<ul>
      								<li>
      									<h2>Tomorrow</h2>
      									<span class="wi wi-day-cloudy text-primary"></span>
      									<div class="statistics">32</div>
      								</li>
      								<li>
      									<h2>Mon</h2>
      									<span class="wi wi-day-cloudy text-danger"></span>
      									<div class="statistics">40</div>
      								</li>
      								<li>
      									<h2>Tue</h2>
      									<span class="wi wi-day-cloudy text-info"></span>
      									<div class="statistics">25</div>
      								</li>
      								<li>
      									<h2>Wed</h2>
      									<span class="wi wi-day-cloudy text-success"></span>
      									<div class="statistics">37</div>
      								</li>
      								<li>
      									<h2>Thu</h2>
      									<span class="wi wi-day-cloudy text-warning"></span>
      									<div class="statistics">15</div>
      								</li>
      								<li>
      									<h2>Fri</h2>
      									<span class="wi wi-day-cloudy"></span>
      									<div class="statistics">21</div>
      								</li>
      							</ul>
      						</div>
      					</div>
      				</div>
      			</section>
      		</div>

      		<div class="col-md-4">
      			<section class="panel panel-default">
      				<div class="clock-panel">
      					<h1>DECEMBER 16</h1>
      					<p class="text-left">2016, Friday</p>
      					<p class="text-left">7:53 PM</p>
      				</div>

      				<ul id="clock">
      					<li id="sec"></li>
      					<li id="hour"></li>
      					<li id="min"></li>
      				</ul>

      				<ul class="clock-category">
      					<li>
      						<a href="#" class="active">
      							<i class="fa fa-clock-o"></i>
      							<span>Clock</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Alarm</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Stop watch</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Timer</span>
      						</a>
      					</li>
      				</ul>
      			</section>
      		</div>
      	</div>

      </div><!-- contentpanel -->

      <%=render "shared/footer"%>
    </div><!-- mainpanel -->
  </div><!-- mainwrapper -->
</section>